apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: saleor-issuer
spec:
  acme:
    server: "https://acme-v02.api.letsencrypt.org/directory"
    email: ag@smart-wolf.com
    privateKeySecretRef:
      name: saleor-issuer
    solvers:
      - http01:
          ingress:
            name: saleor-ingress