---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app: mailhog

resources:
  - mailhog-deployment.yml
  - mailhog-svc.yml

secretGenerator:
  - name: mailhog-smtp
    files:
      - smtp.json
  - name: mailhog-auth
    files:
      - mailhog-auth