---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "10m"
            memory: "128M"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 90
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 10
        ports:
          - containerPort:  80
            name:  nginx
        volumeMounts:
          - mountPath: /var/www/files/media
            name: saleor-media-volume
          - mountPath: /var/www/files/static
            name: saleor-static-volume
          - mountPath: /etc/nginx
            name: nginx-conf
      volumes:
        - name: saleor-media-volume
          persistentVolumeClaim:
            claimName: saleor-media
        - name: saleor-static-volume
          persistentVolumeClaim:
            claimName: saleor-static
        - name: nginx-conf
          configMap:
            name: nginx-conf
