---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: saleor

commonLabels:
  app: saleor-platform

images:
  - name: saleor-image
    newName: skymoore/saleor
    newTag: "3.8.4"
  - name: saleor-dashboard-image
    newName: skymoore/saleor-dashboard
    newTag: "3.8.4"
  - name: saleor-storefront-image
    newName: skymoore/saleor-storefront
    newTag: canary

resources:
  - ../../base
  - ../../saleor
  - ../../saleor-dashboard
  # - ../../saleor-storefront
  - ./nginx
  - ./saleor-dashboard
  - ./saleor
  - infra/ingress.yml

patchesStrategicMerge:
  - infra/storage-class-gp3.yml
  - saleor/saleor.yml
  - saleor-dashboard/saleor-dashboard.yml

configMapGenerator:
  - name: saleor-env
    behavior: replace
    envs:
      - config/backend.env
      - config/common.env
  - name: saleor-dashboard-env
    behavior: replace
    envs:
      - config/dashboard.env

secretGenerator:
  - name: saleor-rsa-key
    behavior: replace
    files:
      - config/private.pem
  - name: saleor-secret
    behavior: replace
    envs:
      - config/secret.env
  - name: db-secret
    behavior: replace
    envs:
      - config/db.env
