apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - nginx.yml
  - nginx-svc.yml

configMapGenerator:
  - name: nginx-conf
    files:
      - nginx.conf

secretGenerator:
  - name: nginx-htpasswd
    files:
      - .htpasswd
