apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: saleor-env
    envs:
      - backend.env
      - common.env

secretGenerator:
  - name: saleor-rsa-key
    files:
      - private.pem
  - name: saleor-secret
    envs:
      - secret.env
